### ISSUE TITLE
Mises à jour ?

### ISSUE THREAD

**Issue by alkino** [etalab/codes-juridiques-francais#3]
Y aura t'il des mises à jour ? C'est assez pratique pour chercher à quel moment un code a changé.

Où est le script qui a permit de générer ça ?

**Comment by RedLens834** [comment]
Les dates des commits sont buggués ? Je serai intéressé également de savoir si ce repo est à jour.
Up 👍 !

**Comment by bboulesteix** [comment]
Bonjour @goutfeb et @alkino, merci d’avoir pris le temps de créer une _issue_. Pour vous répondre, le dépôt en question ne semble plus à jour, non. En tout cas, il ne fait plus l’objet de nouveaux développements de la part des membres d’Etalab. Par conséquent, il va être archivé. 📦
